const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORAGE_KEY='decision-room-v2';
const state={decisions:[],view:'marketing',selectedId:null,roomStage:'intent',filter:'all',selectedEvidence:null,shared:false};

const domainAdapters={
realestate:{name:'Vida & patrimonio',questions:[
'¿Qué cambio quieres conseguir realmente?','¿Qué no quieres sacrificar durante el cambio?','¿Cuánto capital quedará disponible después de costos y obligaciones?','¿Qué condiciones debe cumplir el lugar para funcionar en tu vida diaria?','¿Qué podría volver inviable la transición?'],
evidence:[
['goal','Objetivo y prioridades','Tu propia definición','verified','La decisión debe conservar lo que tú quieres lograr.'],
['capital','Capital neto disponible','Venta probable + deudas + costos','pending','El precio de venta no es lo mismo que el dinero disponible.'],
['documents','Situación documental','Documentos oficiales / revisión profesional','pending','Antes de comprometer dinero hay que confirmar qué se compra y qué puede hacerse.'],
['territory','Comportamiento del lugar','Cartografía + terreno + fuentes oficiales','pending','Agua, acceso, invierno y entorno pueden cambiar habitabilidad y costo.'],
['totalcost','Costo total de llegar a una solución habitable','Cotizaciones por alcance','unknown','La vivienda es solo una parte del costo completo.']],
routes:[
['Avanzar por hitos','Proteger capital y liberar compromiso solo cuando la evidencia crítica está confirmada.','Control de riesgo y liquidez','Más etapas y coordinación'],
['Asegurar destino primero','Validar el lugar y el proyecto antes de cerrar la transición actual.','Continuidad y certeza del destino','Puede requerir más tiempo o capital'],
['Diseñar el cambio completo','Modelar venta, destino, vivienda y reserva como una sola transición.','Coherencia del plan total','Exige más información antes de ejecutar']]},
business:{name:'Negocio & inversión',questions:[
'¿Qué resultado económico estás buscando?','¿Qué tendría que ser cierto para que esto funcione?','¿Qué evidencia demostraría demanda real?','¿Cuál es la pérdida máxima aceptable?','¿Qué puedes probar antes de comprometer más capital?'],
evidence:[
['goal','Resultado y límites','Definición del decisor','verified','Una oportunidad se evalúa contra un objetivo explícito.'],
['demand','Demanda real','Ventas / contratos / comportamiento','pending','Interés declarado no equivale a disposición a pagar.'],
['unit','Economía unitaria','Precio + costos + margen','pending','El crecimiento amplifica un modelo bueno o un problema.'],
['cash','Caja y downside','Flujo de caja + escenarios','pending','Importa cuánto capital puede perderse y durante cuánto tiempo.'],
['capacity','Capacidad operativa','Procesos + personas + proveedores','unknown','La promesa comercial debe poder ejecutarse.']],
routes:[
['Piloto mínimo','Comprar evidencia con el menor compromiso irreversible posible.','Aprendizaje rápido','Resultados iniciales limitados'],
['Validar antes de invertir','Cerrar vacíos de demanda, costos y operación antes de desplegar capital.','Reducción de incertidumbre','Menor velocidad inicial'],
['Ejecución por gates','Preparar el despliegue, liberando recursos solo al cumplir hitos.','Velocidad con control','Más coordinación']]},
mining:{name:'Minería & territorio',questions:[
'¿Qué hipótesis realmente queremos resolver?','¿Qué decisión habilitaría nueva evidencia?','¿Qué observamos y qué estamos interpretando?','¿Qué incertidumbre domina el valor del siguiente paso?','¿Cuál es el costo del siguiente aprendizaje?'],
evidence:[
['goal','Hipótesis y decisión objetivo','Equipo / responsables','verified','Una campaña solo tiene sentido si responde una pregunta que cambia una decisión.'],
['geo','Modelo geológico actual','Mapeo + interpretación + modelos','pending','Hay que separar observación, interpretación e hipótesis.'],
['assays','Datos analíticos y QA/QC','Laboratorio + cadena de custodia','pending','La evidencia analítica necesita procedencia y controles.'],
['rights','Derechos y restricciones','Documentación legal','pending','La opción técnica debe ser compatible con el estado jurídico.'],
['economics','Costo del siguiente aprendizaje','Presupuesto + logística','unknown','La siguiente acción debe comparar información ganada versus costo.']],
routes:[
['Probar hipótesis crítica','Diseñar el siguiente trabajo solo para resolver la incertidumbre dominante.','Valor de información','No cubre todas las preguntas'],
['Campaña escalonada','Aumentar compromiso solo cuando los gates anteriores entregan evidencia suficiente.','Control de capital','Avance gradual'],
['Integrar antes de adquirir','Reconciliar terreno, laboratorio y modelos antes de nueva campaña.','Coherencia del modelo','Retrasa trabajo nuevo']]},
general:{name:'Decisión general',questions:[
'¿Qué quieres conseguir exactamente?','¿Qué no estás dispuesto a perder?','¿Qué tendría que ser cierto para que funcione?','¿Qué información cambiaría tu decisión?','¿Qué parte puedes probar antes de comprometerte?'],
evidence:[
['goal','Objetivo explícito','Tu definición','verified','El sistema necesita saber qué resultado realmente importa.'],
['baseline','Situación actual','Datos / documentos de base','pending','Hay que saber desde dónde partes para comparar el cambio.'],
['constraints','Restricciones reales','Tiempo + dinero + reglas','pending','Las restricciones cambian qué rutas son posibles.'],
['assumptions','Supuestos críticos','Hipótesis a comprobar','unknown','Un supuesto no debe avanzar disfrazado de hecho.'],
['downside','Costo del error','Escenarios / experiencia / datos','unknown','La profundidad de revisión debe crecer con el costo de equivocarse.']],
routes:[
['Prueba reversible','Comprobar primero la hipótesis con menor compromiso posible.','Aprendizaje','No resuelve todo al inicio'],
['Cerrar vacíos primero','Buscar la evidencia que más podría cambiar la decisión.','Calidad de decisión','Menor velocidad'],
['Avanzar por condiciones','Definir gates claros y comprometer recursos por etapas.','Equilibrio velocidad/control','Requiere disciplina de seguimiento']]}
};

function detectDomain(text){const t=text.toLowerCase();if(/casa|parcela|departamento|vivir|vivienda|campo|terreno|propiedad/.test(t))return'realestate';if(/mina|minero|geolog|exploraci|sondaje|mineral/.test(t))return'mining';if(/negocio|invert|empresa|operaci|cliente|producto|mercado|contrat/.test(t))return'business';return'general'}
function uid(){return'D-'+Date.now().toString(36).toUpperCase().slice(-6)}
function save(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify({decisions:state.decisions.filter(d=>!d.transient)}))}catch(e){toast('No pudimos guardar localmente. Puedes exportar la decisión.')}}
function load(){try{const d=JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}');state.decisions=Array.isArray(d.decisions)?d.decisions.map(x=>({...x,demo:String(x.id||'').startsWith('D-DEMO')})):[]}catch(e){state.decisions=[]}}
function b64urlEncode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let bin='';bytes.forEach(b=>bin+=String.fromCharCode(b));return btoa(bin).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64urlDecode(str){let s=str.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s);const bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function sharePayload(d){return {v:2,decision:{...d,sharedAt:Date.now(),transient:true}}}
function buildShareUrl(d){return location.origin+location.pathname+'?share='+encodeURIComponent(b64urlEncode(sharePayload(d)))}
function loadSharedFromUrl(){const p=new URLSearchParams(location.search);const raw=p.get('share');if(!raw)return false;try{const parsed=b64urlDecode(raw);if(!parsed||!parsed.decision)return false;const d={...parsed.decision,id:'S-'+uid().slice(2),transient:true,shared:true};state.decisions.unshift(d);state.selectedId=d.id;state.roomStage='intent';state.shared=true;return true}catch(e){return false}}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function progress(d){let p=16;const ev=d.evidence||[];p+=Math.round(ev.filter(x=>x.status==='verified').length/Math.max(1,ev.length)*34);if(d.selectedRoute)p+=22;if(d.committed)p+=18;if(d.learning)p+=10;return Math.min(100,p)}
function statusOf(d){if(d.learning)return'monitor';if(d.committed||progress(d)>=65)return'ready';return'research'}
function statusLabel(s){return s==='ready'?'Lista para decidir':s==='monitor'?'Monitoreando':'Investigando'}

const mechanismData=[
['Tu intención, intacta','“Quiero cambiar de vida sin comprometer toda mi seguridad financiera.”',[['Objetivo','Más tranquilidad y espacio'],['No sacrificar','Liquidez + acceso cotidiano'],['Horizonte','6–12 meses'],['Decisión final','Humana']]],
['Convertimos la idea en preguntas','No buscamos datos por acumular. Buscamos lo que podría cambiar la decisión.',[['Pregunta crítica','¿Cuánto capital queda realmente?'],['Pregunta crítica','¿Qué hace viable el lugar?'],['Pregunta crítica','¿Qué costos todavía no vemos?'],['Pregunta crítica','¿Qué podría invalidar la ruta?']]],
['Cada dato conserva su procedencia','Lo confirmado y lo pendiente nunca se mezclan.',[['Verificado','Objetivo y restricciones'],['Pendiente','Capital neto'],['Pendiente','Factibilidad del lugar'],['Desconocido','Costo total instalado']]],
['Comparamos rutas, no puntuaciones mágicas','Ves qué optimiza cada camino y qué sacrificas.',[['Ruta A','Avanzar por hitos'],['Ruta B','Asegurar destino primero'],['Ruta C','Diseñar cambio completo'],['Gate','Falta evidencia crítica']]],
['La elección sigue siendo tuya','El sistema puede decir qué está listo. No puede reemplazar lo que tú valoras.',[['Evidencia','Visible'],['Incertidumbre','Explícita'],['Alternativas','Comparables'],['Checkpoint','Tú decides']]],
['La decisión se convierte en trabajo real','Una ruta elegida se descompone en acciones, responsables y nuevos gates.',[['01','Confirmar capital'],['02','Validar opciones'],['03','Cerrar cotizaciones'],['04','Ejecutar por hitos']]]];

function renderMechanism(i=0){const [title,lead,cards]=mechanismData[i];$('#mechanismContent').innerHTML='<div class="demo-title">'+title+'</div><div class="demo-lead">'+lead+'</div><div class="demo-grid">'+cards.map(c=>'<div class="demo-card"><span>'+c[0]+'</span><b>'+c[1]+'</b></div>').join('')+'</div><div class="demo-evidence"><div><i class="ev-ok"></i><b>Fuente primaria / decisión humana</b><span>verificado</span></div><div><i class="ev-pending"></i><b>Evidencia que todavía puede cambiar la ruta</b><span>pendiente</span></div><div><i class="ev-unknown"></i><b>Lo que aún no sabemos</b><span>visible</span></div></div>'}

function showMarketing(){state.view='marketing';$('#marketing').classList.remove('hidden');$('#siteNav').classList.remove('hidden');$('#appShell').classList.add('hidden');document.body.style.overflow='auto'}
function showApp(){state.view='app';$('#marketing').classList.add('hidden');$('#siteNav').classList.add('hidden');$('#appShell').classList.remove('hidden');document.body.style.overflow='hidden';renderDashboard()}
function openDecisionModal(prefill=''){showApp();$('#decisionModal').classList.remove('hidden');$('#decisionIdea').value=prefill;setTimeout(()=>$('#decisionIdea').focus(),50)}
function closeDecisionModal(){$('#decisionModal').classList.add('hidden')}

function seedIfEmpty(){}
function loadDemoDecision(){const d={id:uid(),idea:'¿Deberíamos invertir en una nueva línea de servicio?',constraint:'No comprometer la caja operativa',deadline:'Este trimestre',domain:'business',createdAt:Date.now(),evidence:buildEvidence('business').map((x,i)=>i<2?{...x,status:'verified'}:x),selectedRoute:0,committed:false,learning:'',actions:[],demo:true};state.decisions.unshift(d);state.selectedId=d.id;save();state.roomStage='evidence';renderRoom(d.id)}
function buildEvidence(domain){return domainAdapters[domain].evidence.map((x,i)=>({id:x[0],name:x[1],source:x[2],status:x[3],why:x[4],note:'',critical:i<4}))}
function makeDecision(){const idea=$('#decisionIdea').value.trim();if(!idea){toast('Escribe primero qué estás tratando de decidir');return}const domain=detectDomain(idea);const d={id:uid(),idea,constraint:$('#decisionConstraint').value.trim(),deadline:$('#decisionDeadline').value.trim(),domain,createdAt:Date.now(),evidence:buildEvidence(domain),selectedRoute:null,committed:false,learning:'',actions:[]};state.decisions.unshift(d);state.selectedId=d.id;state.roomStage='intent';save();closeDecisionModal();renderRoom(d.id)}

function renderCounts(){const counts={all:state.decisions.length,research:0,ready:0,monitor:0};state.decisions.forEach(d=>counts[statusOf(d)]++);$('#countAll').textContent=counts.all;$('#countResearch').textContent=counts.research;$('#countReady').textContent=counts.ready;$('#countMonitor').textContent=counts.monitor}
function renderDashboard(){state.selectedId=null;renderCounts();const filtered=state.decisions.filter(d=>state.filter==='all'||statusOf(d)===state.filter);const unresolved=state.decisions.reduce((n,d)=>n+d.evidence.filter(e=>e.critical&&e.status!=='verified').length,0);const first=state.decisions.find(d=>statusOf(d)==='ready')||state.decisions[0];$('#appMain').innerHTML='<div class="dash-head"><div><div class="mini-kicker">Decision workspace</div><h2>Tus decisiones abiertas</h2><p>No necesitas recordar todo. Necesitas saber qué requiere atención.</p></div><button class="btn-main" id="dashNew">+ Nueva decisión</button></div>'+(state.decisions.length?'<div class="attention"><div><span>Qué necesita atención</span><b>'+unresolved+' evidencias críticas todavía abiertas</b><small>'+(first?'Continúa con “'+esc(first.idea).slice(0,72)+(first.idea.length>72?'…':'')+'”':'')+'</small></div>'+(first?'<button id="continueDecision">Continuar →</button>':'')+'</div>':'')+'<div class="dash-stats"><div class="dash-stat"><span>Abiertas</span><strong>'+state.decisions.length+'</strong></div><div class="dash-stat"><span>Listas para decidir</span><strong>'+state.decisions.filter(d=>statusOf(d)==='ready').length+'</strong></div><div class="dash-stat"><span>Evidencia pendiente</span><strong>'+state.decisions.reduce((n,d)=>n+d.evidence.filter(e=>e.status!=='verified').length,0)+'</strong></div></div>'+(filtered.length?'<div class="decision-list">'+filtered.map(d=>'<div class="decision-row" data-id="'+d.id+'"><div><div class="decision-title">'+esc(d.idea)+'</div><div class="decision-sub">'+(d.shared?'SALA COMPARTIDA · ':d.demo?'EJEMPLO · ':'')+d.id+' · '+new Date(d.createdAt).toLocaleDateString('es-CL')+'</div></div><div class="decision-domain">'+domainAdapters[d.domain].name+'</div><div class="decision-progress"><i style="width:'+progress(d)+'%"></i></div><div class="decision-status '+statusOf(d)+'">'+statusLabel(statusOf(d))+'</div></div>').join('')+'</div>':'<div class="empty-state"><span class="empty-orbit"></span><h3>Tu primera decisión empieza con una frase.</h3><p>No necesitas preparar un informe. Escribe qué estás intentando decidir y la sala construirá la estructura contigo.</p><div class="empty-actions"><button class="btn-main" id="emptyNew">Crear mi primera decisión →</button><button class="secondary-small" id="loadDemo">Explorar un ejemplo</button></div></div>');$('#dashNew').onclick=()=>openDecisionModal();if($('#emptyNew'))$('#emptyNew').onclick=()=>openDecisionModal();if($('#loadDemo'))$('#loadDemo').onclick=loadDemoDecision;if($('#continueDecision'))$('#continueDecision').onclick=()=>renderRoom(first.id);$$('.decision-row').forEach(r=>r.onclick=()=>renderRoom(r.dataset.id));renderInspector(null)}
function renderMemoryView(){state.selectedId=null;const entries=state.decisions.filter(d=>d.committed||d.learning).sort((a,b)=>b.createdAt-a.createdAt);$('#appMain').innerHTML='<div class="dash-head"><div><div class="mini-kicker">Decision memory</div><h2>Recordar por qué decidiste</h2><p>La memoria útil no guarda solo respuestas. Guarda contexto, ruta elegida y qué ocurrió después.</p></div></div>'+(entries.length?'<div class="memory-list">'+entries.map((d,i)=>'<div class="memory-entry" data-id="'+d.id+'"><i>'+String(i+1).padStart(2,'0')+'</i><div><span>'+domainAdapters[d.domain].name+' · '+(d.learning?'aprendizaje registrado':'decisión comprometida')+'</span><b>'+esc(d.idea)+'</b><p>'+(d.learning?esc(d.learning):'Ruta elegida: '+esc(domainAdapters[d.domain].routes[d.selectedRoute]?.[0]||'sin ruta')+'. Esperando resultado para cerrar el ciclo.')+'</p></div></div>').join('')+'</div>':'<div class="empty-state"><span class="empty-orbit"></span><h3>La memoria aparece cuando decides y vuelves con el resultado.</h3><p>Compromete una ruta y registra qué ocurrió. Ahí empieza el aprendizaje real del sistema contigo.</p><div class="empty-actions"><button class="secondary-small" id="memoryBack">Volver a decisiones</button></div></div>');$$('.memory-entry').forEach(x=>x.onclick=()=>{state.roomStage='learn';renderRoom(x.dataset.id)});if($('#memoryBack'))$('#memoryBack').onclick=renderDashboard;renderInspector(null)}
function renderPatternsView(){state.selectedId=null;const total=state.decisions.length;const unresolved={};state.decisions.forEach(d=>d.evidence.filter(e=>e.status!=='verified').forEach(e=>unresolved[e.name]=(unresolved[e.name]||0)+1));const top=Object.entries(unresolved).sort((a,b)=>b[1]-a[1]).slice(0,3);const withConstraint=state.decisions.filter(d=>d.constraint).length;const withOutcome=state.decisions.filter(d=>d.learning).length;const domains={};state.decisions.forEach(d=>domains[domainAdapters[d.domain].name]=(domains[domainAdapters[d.domain].name]||0)+1);const topDomain=Object.entries(domains).sort((a,b)=>b[1]-a[1])[0];$('#appMain').innerHTML='<div class="dash-head"><div><div class="mini-kicker">Decision patterns</div><h2>Patrones de cómo estás decidiendo</h2><p>No son juicios sobre ti. Son señales descriptivas de tu propio historial.</p></div></div>'+(total?'<div class="pattern-grid"><div class="pattern-card"><span>Decisiones registradas</span><strong>'+total+'</strong><b>'+ (topDomain?topDomain[0]:'Sin dominio dominante') +'</b><p>Área con más decisiones en este navegador.</p></div><div class="pattern-card"><span>Restricciones explícitas</span><strong>'+Math.round(withConstraint/total*100)+'%</strong><b>'+withConstraint+' de '+total+'</b><p>Cuántas decisiones declaran qué no quieres sacrificar.</p></div><div class="pattern-card"><span>Ciclos cerrados</span><strong>'+withOutcome+'</strong><b>con resultado registrado</b><p>Las decisiones con outcome son las que más enseñan.</p></div><div class="pattern-card"><span>Incertidumbre recurrente</span><strong>'+(top[0]?top[0][1]:'0')+'</strong><b>'+(top[0]?esc(top[0][0]):'Sin patrón todavía')+'</b><p>'+(top.length?'También aparece: '+top.slice(1).map(x=>esc(x[0])).join(' · '):'Crea más decisiones para detectar señales repetidas.')+'</p></div></div>':'<div class="empty-state"><span class="empty-orbit"></span><h3>Todavía no hay historial suficiente.</h3><p>Los patrones se construyen a partir de tus propias decisiones guardadas en este navegador.</p><div class="empty-actions"><button class="secondary-small" id="patternsBack">Volver a decisiones</button></div></div>');if($('#patternsBack'))$('#patternsBack').onclick=renderDashboard;renderInspector(null)}
function renderRoom(id){const d=state.decisions.find(x=>x.id===id);if(!d)return renderDashboard();state.selectedId=id;renderCounts();const stages=[['intent','01','Intención'],['questions','02','Preguntas'],['evidence','03','Evidencia'],['routes','04','Rutas'],['decision','05','Decisión'],['action','06','Acción'],['learn','07','Aprender']];$('#appMain').innerHTML=''+(d.shared?'<div class="shared-banner">Abriste una sala compartida. El enlace contiene una copia del estado; los cambios que hagas aquí quedan en tu navegador.</div>':'')+'<div class="room-head"><div><div class="mini-kicker">'+d.id+' · '+domainAdapters[d.domain].name+'</div><h2>'+esc(d.idea)+'</h2><p>'+(d.constraint?'No sacrificar: '+esc(d.constraint):'Define tus restricciones para mejorar el análisis.')+'</p><div class="room-tools"><button class="room-tool" id="copyPack">Copiar Decision Pack</button><button class="room-tool" id="shareRoom">Compartir sala</button></div></div><div class="decision-status '+statusOf(d)+'">'+statusLabel(statusOf(d))+'</div></div><div class="room-layout"><nav class="room-nav">'+stages.map(s=>'<button data-stage="'+s[0]+'" class="'+(state.roomStage===s[0]?'active':'')+'"><span>'+s[1]+'</span>'+s[2]+'</button>').join('')+'</nav><div class="room-content" id="roomContent"></div></div>';$('.room-nav button').forEach(b=>b.onclick=()=>{state.roomStage=b.dataset.stage;renderRoom(id)});$('#copyPack').onclick=()=>copyDecisionPack(d);$('#shareRoom').onclick=()=>openShare(d);renderRoomStage(d);renderInspectorDecision(d)}

function renderRoomStage(d){const a=domainAdapters[d.domain],c=$('#roomContent');if(state.roomStage==='intent'){c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Intent contract</div><h3>Conservar lo que tú quieres</h3><p>La arquitectura puede cambiar la ruta. No debería borrar el objetivo humano.</p></div><div class="panel"><div class="panel-title">Intención original</div><div class="big-intent">“'+esc(d.idea)+'”</div>'+(d.constraint?'<span class="constraint-chip">No sacrificar · '+esc(d.constraint)+'</span>':'')+(d.deadline?'<span class="constraint-chip">Horizonte · '+esc(d.deadline)+'</span>':'')+'</div><div class="panel"><div class="panel-title">Regla de la sala</div><div style="font-size:10px;line-height:1.5">Toda evidencia, ruta o acción se evalúa contra esta intención. Si el objetivo cambia, la decisión debe reabrirse.</div></div>';return}
if(state.roomStage==='questions'){c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Decision framing</div><h3>Las preguntas que podrían cambiar la decisión</h3><p>No se trata de investigar todo. Se trata de identificar qué vale la pena saber antes de comprometerte.</p></div><div class="question-list">'+a.questions.map((q,i)=>'<div class="question"><i>'+(i+1)+'</i><div><b>'+q+'</b><p>'+questionHint(i,d.domain)+'</p></div><span class="question-status">'+(i===0?'definida':'abierta')+'</span></div>').join('')+'</div>';return}
if(state.roomStage==='evidence'){c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Evidence graph</div><h3>Qué sabemos. Y qué todavía no.</h3><p>Abre cualquier evidencia para editar fuente, estado y observaciones.</p></div><div class="evidence-list">'+d.evidence.map(e=>'<div class="evidence-item '+e.status+'" data-eid="'+e.id+'"><i></i><div><b>'+e.name+'</b><p>'+esc(e.source)+'</p></div><span class="ev-tag">'+e.status+'</span></div>').join('')+'</div>';$$('.evidence-item').forEach(x=>x.onclick=()=>renderEvidenceInspector(d,x.dataset.eid));return}
if(state.roomStage==='routes'){c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Comparable paths</div><h3>No una respuesta. Rutas con trade-offs.</h3><p>Seleccionar una ruta no la convierte en verdad. Solo define qué camino quieres examinar para avanzar.</p></div><div class="route-list">'+a.routes.map((r,i)=>'<div class="route-card '+(d.selectedRoute===i?'selected':'')+'"><div class="route-top"><div><h4>'+r[0]+'</h4><p>'+r[1]+'</p></div><button class="select-route" data-route="'+i+'">'+(d.selectedRoute===i?'Seleccionada':'Explorar esta ruta')+'</button></div><div class="route-meta"><div><span>Optimiza</span><b>'+r[2]+'</b></div><div><span>Trade-off</span><b>'+r[3]+'</b></div></div></div>').join('')+'</div>';$$('.select-route').forEach(b=>b.onclick=()=>{d.selectedRoute=Number(b.dataset.route);save();renderRoom(d.id)});return}
if(state.roomStage==='decision'){const pending=d.evidence.filter(e=>e.critical&&e.status!=='verified');const route=d.selectedRoute!==null?a.routes[d.selectedRoute]:null;c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Human checkpoint</div><h3>¿Está suficientemente pensada para comprometerte?</h3><p>El gate no decide por ti. Te muestra qué tan expuesta está la elección a evidencia todavía pendiente.</p></div><div class="decision-gate"><span>'+(pending.length?'REVIEW · '+pending.length+' evidencias críticas pendientes':'READY · evidencia crítica cubierta')+'</span><h4>'+(route?route[0]:'Primero selecciona una ruta')+'</h4><p>'+(route?route[1]:'Compara las rutas y elige cuál quieres llevar al checkpoint humano.')+'</p><div class="gate-actions">'+(route?'<button class="commit-btn" id="commitDecision">'+(d.committed?'Decisión registrada ✓':'Registrar mi decisión')+'</button><button class="hold-btn" id="holdDecision">Seguir investigando</button>':'')+'</div></div>';if(route){$('#commitDecision').onclick=()=>{d.committed=true;d.actions=buildActions(d);save();toast('Decisión registrada. Ahora se convierte en acciones.');state.roomStage='action';renderRoom(d.id)};$('#holdDecision').onclick=()=>{state.roomStage='evidence';renderRoom(d.id)}}return}
if(state.roomStage==='action'){if(!d.committed){c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Action layer</div><h3>Todavía no hay una decisión comprometida.</h3><p>Selecciona una ruta y pasa por el checkpoint humano antes de generar el plan.</p></div>';return}c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Action layer</div><h3>La decisión ahora tiene trabajo que hacer.</h3><p>Completar una acción puede crear evidencia nueva y reabrir la decisión si cambia un supuesto importante.</p></div><div class="action-list">'+d.actions.map((x,i)=>'<div class="action-item"><i>'+(i+1)+'</i><div><b>'+x.title+'</b><p>'+x.why+'</p></div><input type="checkbox" data-action="'+i+'" '+(x.done?'checked':'')+'></div>').join('')+'</div>';$$('[data-action]').forEach(ch=>ch.onchange=()=>{d.actions[Number(ch.dataset.action)].done=ch.checked;save();renderInspectorDecision(d)});return}
if(state.roomStage==='learn'){c.innerHTML='<div class="room-section-head"><div class="mini-kicker">Outcome loop</div><h3>¿Qué ocurrió después?</h3><p>Guardar el resultado convierte una conversación en memoria de decisión.</p></div><div class="learning-card"><textarea id="learningText" placeholder="Ej.: la demanda real fue mayor a lo esperado; el supuesto de precio quedó validado, pero el costo operativo fue 18% superior...">'+esc(d.learning||'')+'</textarea><div class="learning-actions"><button class="small-primary" id="saveLearning">Guardar aprendizaje</button></div></div>';$('#saveLearning').onclick=()=>{d.learning=$('#learningText').value.trim();save();toast('Aprendizaje guardado en la memoria de decisión');renderRoom(d.id)};return}}

function questionHint(i,domain){const hints={realestate:['Define la vida que intentas construir, no solo la propiedad.','Haz visibles los límites antes de enamorarte de una opción.','El capital neto cambia todas las rutas disponibles.','La habitabilidad es más amplia que una foto bonita.','Una buena ruta también define cuándo detenerse.'],business:['Resultado, no actividad.','Convierte la tesis en condiciones falsables.','Busca comportamiento observable.','Define downside antes de entusiasmo.','Compra aprendizaje antes de escala.'],mining:['Toda campaña debe responder una decisión.','Define el gate que la nueva evidencia habilitaría.','Separa observación de interpretación.','Ataca primero la incertidumbre dominante.','Compara valor de información contra costo.'],general:['Nombra el resultado que de verdad importa.','Toda decisión optimiza algo y sacrifica otra cosa.','Convierte intuiciones en condiciones comprobables.','No toda información vale el mismo esfuerzo.','Prueba primero lo reversible.']};return hints[domain][i]}
function buildActions(d){const base=[['Cerrar evidencia crítica','Resolver las fuentes pendientes que podrían invalidar la ruta.'],['Definir umbral de avance','Acordar qué debe cumplirse antes de comprometer más recursos.'],['Asignar responsables','Separar qué hace el sistema, qué hace una persona y qué requiere especialista.'],['Ejecutar primer paso reversible','Avanzar con la acción que compra más información con menor downside.'],['Revisar la decisión','Volver a la sala cuando aparezca nueva evidencia.']];return base.map(x=>({title:x[0],why:x[1],done:false}))}

function renderInspector(nullObj){$('#inspector').innerHTML='<div class="inspector-empty"><span class="inspect-orbit"></span><b>Contexto visible</b><p>Selecciona una decisión o evidencia para inspeccionar lo que opera detrás.</p></div>'}
function renderInspectorDecision(d){const verified=d.evidence.filter(e=>e.status==='verified').length,pending=d.evidence.filter(e=>e.status==='pending').length,unknown=d.evidence.filter(e=>e.status==='unknown').length;$('#inspector').innerHTML='<div class="inspector-card"><span>DECISION ID</span><b>'+d.id+'</b><p>'+domainAdapters[d.domain].name+'</p></div><div class="inspector-card"><span>EVIDENCIA</span><b>'+verified+' verificada · '+pending+' pendiente · '+unknown+' desconocida</b><p>La barra de progreso no es un score de “calidad”. Solo refleja cuánto del flujo está estructurado.</p></div><div class="inspector-card"><span>PROGRESO</span><b>'+progress(d)+'%</b><div class="decision-progress" style="margin-top:8px"><i style="width:'+progress(d)+'%"></i></div></div><div class="inspector-card"><span>PRINCIPIO</span><b>La decisión sigue siendo humana.</b><p>El sistema puede bloquear claims insuficientes. No puede decidir qué vida, riesgo o trade-off debes preferir.</p></div>'}
function renderEvidenceInspector(d,eid){const e=d.evidence.find(x=>x.id===eid);if(!e)return;state.selectedEvidence=eid;$('#inspector').innerHTML='<div class="inspector-card"><span>EVIDENCIA</span><b>'+e.name+'</b><p>'+e.why+'</p></div><div class="inspector-card"><span>PROCEDENCIA</span><b>Fuente declarada</b><p>'+esc(e.source)+'</p><div class="source-editor"><input id="sourceInput" value="'+esc(e.source)+'"><select id="statusSelect"><option value="verified" '+(e.status==='verified'?'selected':'')+'>Verificada</option><option value="pending" '+(e.status==='pending'?'selected':'')+'>Pendiente</option><option value="unknown" '+(e.status==='unknown'?'selected':'')+'>Desconocida</option></select><button class="small-primary" id="saveEvidence">Actualizar evidencia</button></div></div><div class="inspector-card"><span>LIMITACIÓN</span><b>'+(e.critical?'Puede cambiar la decisión':'Contextual')+'</b><p>Si el origen o la condición cambia, la sala debe reevaluar las rutas que dependan de esta evidencia.</p></div>';$('#saveEvidence').onclick=()=>{e.source=$('#sourceInput').value.trim()||e.source;e.status=$('#statusSelect').value;save();toast('Evidencia actualizada');renderRoom(d.id);renderEvidenceInspector(d,eid)}}

function decisionPack(d){const a=domainAdapters[d.domain],route=d.selectedRoute!==null?a.routes[d.selectedRoute]:null;return ['DECISION ROOM · '+d.id,'','INTENCIÓN',d.idea,d.constraint?'No sacrificar: '+d.constraint:'',d.deadline?'Horizonte: '+d.deadline:'','','EVIDENCIA',...d.evidence.map(e=>'- ['+e.status.toUpperCase()+'] '+e.name+' — '+e.source),'','RUTA'+(route?' ELEGIDA':'S'),route?route[0]+' — '+route[1]:a.routes.map(r=>'- '+r[0]+' — '+r[1]).join('\n'),'','ESTADO','Evidencia crítica pendiente: '+d.evidence.filter(e=>e.critical&&e.status!=='verified').length,d.committed?'Checkpoint humano: decisión registrada':'Checkpoint humano: pendiente',...(d.learning?['','RESULTADO',d.learning]:[])].filter(x=>x!==false).join('\n')}
async function copyDecisionPack(d){const text=decisionPack(d);try{await navigator.clipboard.writeText(text);toast('Decision Pack copiado')}catch(e){const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('Decision Pack copiado')}}
function openShare(d){if(!d){toast('Abre una decisión antes de compartirla');return}$('#shareUrl').value=buildShareUrl(d);$('#shareModal').classList.remove('hidden')}
function closeShare(){$('#shareModal').classList.add('hidden')}
async function copyShare(){const u=$('#shareUrl').value;try{await navigator.clipboard.writeText(u);toast('Enlace copiado')}catch(e){$('#shareUrl').select();document.execCommand('copy');toast('Enlace copiado')}}
function openFeedback(){$('#feedbackModal').classList.remove('hidden');setTimeout(()=>$('#feedbackText').focus(),50)}
function closeFeedback(){$('#feedbackModal').classList.add('hidden')}
function prepareFeedback(){const t=$('#feedbackText').value.trim();if(!t){toast('Cuéntanos primero qué deberíamos mejorar');return}const ctx=$('#feedbackContext').value.trim(),impact=$('#feedbackImpact').value;const subject='Sugerencia para Decision Room';const body=['SUGERENCIA',t,'',ctx?'CONTEXTO\n'+ctx:'','IMPACTO\n'+impact,'','Decision Room V2 · '+new Date().toISOString()].filter(Boolean).join('\n');location.href='mailto:contacto@deepanalytica.cl?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body)}
function exportData(){const payload=state.selectedId?state.decisions.find(d=>d.id===state.selectedId):state.decisions;const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=state.selectedId?'decision-'+state.selectedId+'.json':'decision-room-export.json';a.click();URL.revokeObjectURL(a.href)}
function openArchitecture(){$('#architectureDrawer').classList.remove('hidden')}
function closeArchitecture(){$('#architectureDrawer').classList.add('hidden')}

function wire(){
renderMechanism(0);$$('[data-step-card]').forEach((c,i)=>{c.onmouseenter=()=>{$$('[data-step-card]').forEach(x=>x.classList.remove('active'));c.classList.add('active');renderMechanism(i)}});$$('[data-open-room]').forEach(b=>b.onclick=()=>openDecisionModal());$('[data-demo]').onclick=()=>openDecisionModal('Quiero decidir si debo invertir en una nueva línea de negocio sin poner en riesgo la caja actual.');
$$('[data-founder]').forEach(b=>b.onclick=()=>$('#founderModal').classList.remove('hidden'));$$('[data-close-founder]').forEach(b=>b.onclick=()=>$('#founderModal').classList.add('hidden'));
$('[data-home]').onclick=showMarketing;$('#newDecisionBtn').onclick=()=>openDecisionModal();$$('[data-close-modal]').forEach(b=>b.onclick=closeDecisionModal);$$('[data-prompt]').forEach(b=>b.onclick=()=>$('#decisionIdea').value=b.dataset.prompt);$('#createDecisionBtn').onclick=makeDecision;$('#decisionIdea').addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')makeDecision()});
$$('.side-link').forEach(b=>b.onclick=()=>{if(b.dataset.view==='dashboard'){state.filter='all';renderDashboard()}else if(b.dataset.view==='memory'){renderMemoryView()}else if(b.dataset.view==='patterns'){renderPatternsView()}});$$('.side-filter').forEach(b=>b.onclick=()=>{state.filter=b.dataset.filter;renderDashboard()});
$('#architectureBtn').onclick=openArchitecture;$('#closeArchitecture').onclick=closeArchitecture;$('#exportBtn').onclick=exportData;$('#shareDecisionBtn').onclick=()=>{const d=state.selectedId&&state.decisions.find(x=>x.id===state.selectedId);if(d)openShare(d);else toast('Abre una decisión antes de compartirla')};$('#feedbackBtn').onclick=openFeedback;
if($('.inspect-btn'))$('.inspect-btn').onclick=openArchitecture;
$$('[data-close-share]').forEach(b=>b.onclick=closeShare);$('#copyShareBtn').onclick=copyShare;$$('[data-close-feedback]').forEach(b=>b.onclick=closeFeedback);$('#sendFeedbackBtn').onclick=prepareFeedback;
$('#decisionModal').onclick=e=>{if(e.target===$('#decisionModal'))closeDecisionModal()};$('#founderModal').onclick=e=>{if(e.target===$('#founderModal'))$('#founderModal').classList.add('hidden')};$('#shareModal').onclick=e=>{if(e.target===$('#shareModal'))closeShare()};$('#feedbackModal').onclick=e=>{if(e.target===$('#feedbackModal'))closeFeedback()};$('#architectureDrawer').onclick=e=>{if(e.target===$('#architectureDrawer'))closeArchitecture()};
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDecisionModal();closeShare();closeFeedback();closeArchitecture();$('#founderModal').classList.add('hidden')}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openDecisionModal()}});
}
load();seedIfEmpty();const sharedLoaded=loadSharedFromUrl();wire();if(sharedLoaded){showApp();renderRoom(state.selectedId)}